apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  entryPoints:
    - web
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.app.name }}-tls
  routes:
    - match: Host(`{{ .Values.domain }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          namespace: frontend
          port: 80


