apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: {{ .Values.ingress.certIssuer }}
    domains:
      - main: {{ .Values.domain }}
  routes:
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: frontend
          namespace: frontend
          port: 80


