apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.name }}
spec:
  serviceName: {{ .Values.app.name }}
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.adminPasswordSecret }}
                  key: keycloak-admin-password
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
  volumeClaimTemplates:
    - metadata:
        name: keycloak-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.keycloakSize }}
