apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: keycloak
  serviceName: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          args:
            - start-dev
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://service-postgres:5432/{{ .Values.postgres.database }}"
            - name: KC_DB_USERNAME
              value: {{ .Values.postgres.username }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecret }}
                  key: postgres-password
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.adminPasswordSecret }}
                  key: keycloak-admin-password
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.keycloak.resources.requests.cpu }}
              memory: {{ .Values.keycloak.resources.requests.memory }}
            limits:
              cpu: {{ .Values.keycloak.resources.limits.cpu }}
              memory: {{ .Values.keycloak.resources.limits.memory }}
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.persistence.size }}