apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
spec:
  serviceName: service-keycloak
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          args:
            - start
            - --optimized
            - --db=postgres
            - --db-url=jdbc:postgresql://service-postgres:5432/keycloakdb
            - --db-username=keycloak
            - --db-password=$(KC_DB_PASSWORD)
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.adminPasswordSecret }}
                  key: keycloak-admin-password
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://service-postgres:5432/{{ .Values.postgres.database }}"
            - name: KC_DB_USERNAME
              value: {{ .Values.postgres.username }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecret }}
                  key: postgres-password
            - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
              value: "true"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
  volumeClaimTemplates:
    - metadata:
        name: keycloak-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi