apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: {{ .Values.keycloak.ingress.certIssuer }}
spec:
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.app.name }}-tls
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: 8080
