apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VotingM7011E/gitops.git
    targetRevision: main
    path: ingress
    helm:
      valueFiles:
        - ../environments/dev/ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true