apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VotingM7011E/gitops.git
    targetRevision: main
    path: postgresql-db
    helm:
      valueFiles:
        - ../environments/dev/postgresql-db.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql-db-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

