apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  destination:
       server: https://kubernetes.default.svc
    namespace: rabbitmq-dev
  source:
    repoURL: https://github.com/VotingM7011E/gitops.git
    targetRevision: main
    path: rabbitmq
    helm:
      releaseName: rabbitmq-dev
      valueFiles:
        - ../environments/dev/rabbitmq.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
