---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Apply secrets first

spec:
  encryptedData:
    keycloak-admin-password: AgAzEC4k8BJjw4b/SvYhaRfCljgr91YREnWUc9QPogvw65XaqZJ4aW8fa4WCihQTXyyGBnOvEEU78aS0RqEXgbIJhuNU+AESjdsYE8KbW1T0Xy8VmM4w8QxALjfwKcFsCsRVjg5Os4qM8Qg4NUKzLo3j90sfRlxWjsddQjbvbKqu5R9ghJwcX+B95QN/xOsTjmMZIGdtQRc7mduPW1FtjZp0sg5S06I/bXq2m9kIt4m3+ltNxBI0TkiNAS9vQ/G57edp+HdFwFvZkB5/VxTUR0ixvhcYy4oQactE2Al4w/vvo3R22hgow2PbJSo22ZWcXX9+VwzfAIVLOorwf1Ts4zcmK7zwe8x/SghL1nQZe3TqsGidwEiLEo38X1eaXWMIMRd9OXCImPZGUTNHpr/gdaAsxPdEXONYQQCrREIKviS0J3PCeV5bg/U0XKeT+YbPpNfBc0Sx/cp33kExIBQDOuuT3svp/cJpqHfbAIKwu84+wBWUAL1uR1vIyJzfIOumn2CM7707dQCZZ7SHZu9wJnZa5aen7DDRDdeAcc8bkWksdNpqhh9NZvEJ+JI4YpbOv2FfVgmaVZwY+uELvFej8X45NuTcfLcdges5PEf0Y2M6Y8EZkTlmo6PY7bj8caV7GkYwTFDTT0i3PED9Q8tSZobs27Q1zkJBgcR5UnT9gWUv4buZh2GrjORZcZEScejKNcIvdR4lsglo189fbJ5itKg7
    postgres-password: AgBvtC6ZCDDunGEG3DlrvbaJjo42DoQ/s3rCT26aOWNb091PelxkVpDxObpkcqHNthViszPw7o6LEZm0yq9uwaf1CUCwtAo+GafMm/SnMBFIwT0mwMzTF3eb0V6/xivVSrD9yYmjd+MlPaeU9b4JhEOx4IynyXvXaayu8MoqrgR+SXJh4Fl2OtSALI27hAfnPF0BEZZoqQg1D+HyFOaw9IUCPpKXYAFdzTh5L04IfR9xq/y+N84xmBUOi+2Krnj0oF512piSfm+INopCVR2iqr68P61B63AA121OwcX2J8q+crp5XUXEBIu8QudbXFjNBe5ce6mQ1YHCEtK7p2mNrgIu42CPQhvIcRYpbASwXIXhC6+Pe/d6XdeHgL52WeWy59HYAdx3qkFO7epY7JOASZT61PV4rbf1LgfxHoQ90fhP2DQhrzhoPvq9rhqTyKII8eUKJGQiW3ZR6vMoCxtJv/JAow4JV2C/jBVNLkawOnY5ZAGEeqT43GM7pn8vUpeyNh8cwOkG5dBQM6BZLMYYRngNby24/aolTlE78jSIH36bcnEqwc+5qwp9VTTbpB4MjG49NWf+zoVoU7pld4+pPLl+txYQLsmg/w3e0VjnhXmitcDEeNybJevFB62+CuWvoQbiIlzc4gDCsyUHy5Qtnh4ZO1z90eBbMLe8oRpl57ONa+NuaZZNxwRnSpRwqH1uAo4eITiCQVzeBYd6HHxBu3Gr
  template:
    metadata:
      name: keycloak-secrets
      namespace: keycloak
