apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VotingM7011E/gitops.git
    targetRevision: main
    path: todo-app
    helm:
      valueFiles:
        - ../environments/dev/todo.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true