apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.serviceName }}
  labels:
    app: {{ .Values.mongodb.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongodb.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.serviceName }}
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.mongodb.username }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.mongodb.password }}"
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.mongodb.database }}"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
