# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-backend
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 8000
      targetPort: backend
      protocol: TCP

# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 8080
      targetPort: frontend
      protocol: TCP